# Constantes/macros de configuração
MIN_CIDADES = 5
MAX_CIDADES = 25
MIN_POPULACAO = 25
MAX_POPULACAO = 100
MIN_MAX_GERACOES = 10
MAX_MAX_GERACOES = 10000
MIN_GERACOES_SEM_MELHORIA = 5
MAX_GERACOES_SEM_MELHORIA = 1000
LIM_CARRO_ELETRICO = 120
TIPO_TRANSPORTE_AVIAO = 1
TIPO_TRANSPORTE_TREM = 2
TIPO_TRANSPORTE_CARRO_ELETRICO = 3
TIPO_TRANSPORTE_CAMINHAO = 4
PESO_TEMPO = 0.3
PROB_MUTACAO = 0.5

# Constantes/macros de velocidade média dos transportes (em pixels por unidade de tempo)
VELOC_AVIAO = 250 # 50 V/C
VELOC_TREM = 80 # 40 V/C
VELOC_CARRO_ELETRICO = 75 # 75 V/C
VELOC_CAMINHAO = 60 # 20 V/C

# Constantes/macros de custo médio dos transportes (em R$ por pixel)
CUSTO_AVIAO = 5
CUSTO_TREM = 2
CUSTO_CARRO_ELETRICO = 1
CUSTO_CAMINHAO = 3

# Constantes/macros de configuração do Pygame
LARGURA_TELA = 1060
ALTURA_TELA = 660
OFFSET_X_GRAFICO = 400
MARGEM = 30
COR_BRANCO = (255, 255, 255)
COR_AZUL = (0, 0, 255)
COR_CINZA = (200, 200, 200)
COR_PRETO = (0, 0, 0)
COR_VERDE = (0, 255, 0)
COR_VERMELHA = (255, 0, 0)
ESPESSURA_AVIAO = 5
ESPESSURA_TREM = 4
ESPESSURA_CARRO_ELETRICO = 2
ESPESSURA_CAMINHAO = 3
RAIO = 7
FPS = 30